/**
 * 3D-printing file format exporters. All functions are pure: they take an
 * indexed triangle mesh (positions in millimeters, CCW-wound indices) and
 * return file contents. Zipping for 3MF is done by the caller (fflate).
 */

function triangleNormal(px, py, pz, qx, qy, qz, rx, ry, rz) {
  const ux = qx - px, uy = qy - py, uz = qz - pz;
  const vx = rx - px, vy = ry - py, vz = rz - pz;
  let nx = uy * vz - uz * vy;
  let ny = uz * vx - ux * vz;
  let nz = ux * vy - uy * vx;
  const len = Math.hypot(nx, ny, nz);
  if (len > 0) { nx /= len; ny /= len; nz /= len; }
  return [nx, ny, nz];
}

/** Binary STL (units are implicitly millimeters for slicers). */
export function toBinarySTL(positions, indices, headerText = 'terrain-stl-generator') {
  const triCount = indices.length / 3;
  const buffer = new ArrayBuffer(84 + triCount * 50);
  const view = new DataView(buffer);
  const headerBytes = new TextEncoder().encode(headerText.slice(0, 80));
  new Uint8Array(buffer, 0, headerBytes.length).set(headerBytes);
  view.setUint32(80, triCount, true);
  let off = 84;
  for (let t = 0; t < triCount; t++) {
    const a = indices[t * 3] * 3, b = indices[t * 3 + 1] * 3, c = indices[t * 3 + 2] * 3;
    const n = triangleNormal(
      positions[a], positions[a + 1], positions[a + 2],
      positions[b], positions[b + 1], positions[b + 2],
      positions[c], positions[c + 1], positions[c + 2]
    );
    view.setFloat32(off, n[0], true); view.setFloat32(off + 4, n[1], true); view.setFloat32(off + 8, n[2], true);
    off += 12;
    for (const vi of [a, b, c]) {
      view.setFloat32(off, positions[vi], true);
      view.setFloat32(off + 4, positions[vi + 1], true);
      view.setFloat32(off + 8, positions[vi + 2], true);
      off += 12;
    }
    view.setUint16(off, 0, true);
    off += 2;
  }
  return buffer;
}

/** ASCII STL — much larger files, but human-readable. */
export function toAsciiSTL(positions, indices, name = 'terrain') {
  const out = [`solid ${name}`];
  const triCount = indices.length / 3;
  const f = (x) => (Object.is(x, -0) ? 0 : x).toPrecision(7);
  for (let t = 0; t < triCount; t++) {
    const a = indices[t * 3] * 3, b = indices[t * 3 + 1] * 3, c = indices[t * 3 + 2] * 3;
    const n = triangleNormal(
      positions[a], positions[a + 1], positions[a + 2],
      positions[b], positions[b + 1], positions[b + 2],
      positions[c], positions[c + 1], positions[c + 2]
    );
    out.push(`  facet normal ${f(n[0])} ${f(n[1])} ${f(n[2])}`);
    out.push('    outer loop');
    for (const vi of [a, b, c]) {
      out.push(`      vertex ${f(positions[vi])} ${f(positions[vi + 1])} ${f(positions[vi + 2])}`);
    }
    out.push('    endloop');
    out.push('  endfacet');
  }
  out.push(`endsolid ${name}`);
  return out.join('\n');
}

/** Wavefront OBJ. */
export function toOBJ(positions, indices, name = 'terrain') {
  const out = [`# ${name} — generated by terrain-stl-generator (units: mm)`, `o ${name}`];
  const f = (x) => +x.toFixed(5);
  for (let v = 0; v < positions.length; v += 3) {
    out.push(`v ${f(positions[v])} ${f(positions[v + 1])} ${f(positions[v + 2])}`);
  }
  for (let t = 0; t < indices.length; t += 3) {
    out.push(`f ${indices[t] + 1} ${indices[t + 1] + 1} ${indices[t + 2] + 1}`);
  }
  return out.join('\n');
}

/** Binary little-endian PLY. */
export function toPLY(positions, indices, name = 'terrain') {
  const vertexCount = positions.length / 3;
  const triCount = indices.length / 3;
  const header =
    'ply\nformat binary_little_endian 1.0\n' +
    `comment ${name} — generated by terrain-stl-generator (units: mm)\n` +
    `element vertex ${vertexCount}\n` +
    'property float x\nproperty float y\nproperty float z\n' +
    `element face ${triCount}\n` +
    'property list uchar uint vertex_indices\n' +
    'end_header\n';
  const headerBytes = new TextEncoder().encode(header);
  const buffer = new ArrayBuffer(headerBytes.length + vertexCount * 12 + triCount * 13);
  new Uint8Array(buffer).set(headerBytes);
  const view = new DataView(buffer);
  let off = headerBytes.length;
  for (let v = 0; v < positions.length; v++) {
    view.setFloat32(off, positions[v], true);
    off += 4;
  }
  for (let t = 0; t < indices.length; t += 3) {
    view.setUint8(off, 3);
    view.setUint32(off + 1, indices[t], true);
    view.setUint32(off + 5, indices[t + 1], true);
    view.setUint32(off + 9, indices[t + 2], true);
    off += 13;
  }
  return buffer;
}

/**
 * Color 3MF: per-triangle colors via core-spec <basematerials>, the most
 * widely supported route for multi-color slicers (Bambu/Prusa/Orca).
 *
 * @param {string[]} palette  hex colors like "#RRGGBB"
 * @param {Uint8Array|number[]} triMaterial  palette index per triangle
 * @returns {{[path: string]: string}} files for the caller to zip
 */
export function to3MFColorFiles(positions, indices, palette, triMaterial, name = 'terrain') {
  const f = (x) => +x.toFixed(5);
  const verts = [];
  for (let v = 0; v < positions.length; v += 3) {
    verts.push(`<vertex x="${f(positions[v])}" y="${f(positions[v + 1])}" z="${f(positions[v + 2])}"/>`);
  }
  const tris = [];
  for (let t = 0, k = 0; t < indices.length; t += 3, k++) {
    tris.push(`<triangle v1="${indices[t]}" v2="${indices[t + 1]}" v3="${indices[t + 2]}" pid="2" p1="${triMaterial[k]}"/>`);
  }
  const mats = palette
    .map((hex, k) => `<base name="band-${k}" displaycolor="${hex}"/>`)
    .join('');
  const model =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n' +
    ` <metadata name="Title">${name}</metadata>\n` +
    ' <metadata name="Application">terrain-stl-generator</metadata>\n' +
    ' <resources>\n' +
    `  <basematerials id="2">${mats}</basematerials>\n` +
    `  <object id="1" type="model" name="${name}" pid="2" pindex="0">\n` +
    '   <mesh>\n' +
    `    <vertices>${verts.join('')}</vertices>\n` +
    `    <triangles>${tris.join('')}</triangles>\n` +
    '   </mesh>\n' +
    '  </object>\n' +
    ' </resources>\n' +
    ' <build><item objectid="1"/></build>\n' +
    '</model>\n';
  const base = to3MFFiles(new Float32Array(0), new Uint32Array(0), name);
  return { ...base, '3D/3dmodel.model': model };
}

/**
 * Binary glTF (.glb) with optional planar-mapped texture. Positions are
 * converted from the app's z-up millimeters to glTF's y-up meters-agnostic
 * space (we keep mm units; viewers just scale).
 *
 * @param {?Float32Array} uvs      2 floats per vertex, or null
 * @param {?Uint8Array} texturePng PNG bytes to embed, or null for a plain material
 * @returns {ArrayBuffer} GLB container
 */
export function toGLB(positions, indices, uvs = null, texturePng = null, name = 'terrain') {
  const vertexCount = positions.length / 3;
  // z-up (x east, y north, z up) -> y-up (x east, y up, z south)
  const pos = new Float32Array(positions.length);
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  for (let v = 0; v < vertexCount; v++) {
    const x = positions[v * 3], y = positions[v * 3 + 1], z = positions[v * 3 + 2];
    const p = [x, z, -y];
    for (let k = 0; k < 3; k++) {
      pos[v * 3 + k] = p[k];
      if (p[k] < min[k]) min[k] = p[k];
      if (p[k] > max[k]) max[k] = p[k];
    }
  }

  const align = (n) => (n + 3) & ~3;
  const chunks = [];
  let byteOffset = 0;
  const addChunk = (bytes) => {
    const view = { byteOffset, byteLength: bytes.byteLength };
    chunks.push(bytes);
    byteOffset = align(byteOffset + bytes.byteLength);
    return view;
  };

  const posView = addChunk(new Uint8Array(pos.buffer));
  const idxView = addChunk(new Uint8Array(new Uint32Array(indices).buffer));
  const uvView = uvs && texturePng ? addChunk(new Uint8Array(new Float32Array(uvs).buffer)) : null;
  const imgView = texturePng ? addChunk(texturePng) : null;

  const bufferViews = [
    { buffer: 0, byteOffset: posView.byteOffset, byteLength: posView.byteLength, target: 34962 },
    { buffer: 0, byteOffset: idxView.byteOffset, byteLength: idxView.byteLength, target: 34963 },
  ];
  const accessors = [
    { bufferView: 0, componentType: 5126, count: vertexCount, type: 'VEC3', min, max },
    { bufferView: 1, componentType: 5125, count: indices.length, type: 'SCALAR' },
  ];
  const attributes = { POSITION: 0 };
  const material = { name, pbrMetallicRoughness: { metallicFactor: 0, roughnessFactor: 0.95 }, doubleSided: false };
  const gltf = {
    asset: { version: '2.0', generator: 'terrain-stl-generator' },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0, name }],
    meshes: [{ primitives: [{ attributes, indices: 1, material: 0 }] }],
    materials: [material],
    accessors,
    bufferViews,
    buffers: [{ byteLength: byteOffset }],
  };
  if (uvView && imgView) {
    bufferViews.push({ buffer: 0, byteOffset: uvView.byteOffset, byteLength: uvView.byteLength, target: 34962 });
    accessors.push({ bufferView: 2, componentType: 5126, count: vertexCount, type: 'VEC2' });
    attributes.TEXCOORD_0 = accessors.length - 1;
    bufferViews.push({ buffer: 0, byteOffset: imgView.byteOffset, byteLength: imgView.byteLength });
    gltf.images = [{ bufferView: bufferViews.length - 1, mimeType: 'image/png' }];
    gltf.samplers = [{ magFilter: 9729, minFilter: 9987, wrapS: 33071, wrapT: 33071 }];
    gltf.textures = [{ sampler: 0, source: 0 }];
    material.pbrMetallicRoughness.baseColorTexture = { index: 0 };
  } else {
    material.pbrMetallicRoughness.baseColorFactor = [0.55, 0.5, 0.45, 1];
  }

  const bin = new Uint8Array(byteOffset);
  let off = 0;
  for (const c of chunks) {
    bin.set(c, off);
    off = align(off + c.byteLength);
  }
  const jsonBytes = new TextEncoder().encode(JSON.stringify(gltf));
  const jsonPadded = new Uint8Array(align(jsonBytes.length));
  jsonPadded.fill(0x20); // pad JSON chunk with spaces
  jsonPadded.set(jsonBytes);

  const total = 12 + 8 + jsonPadded.length + 8 + bin.length;
  const out = new ArrayBuffer(total);
  const dv = new DataView(out);
  const u8 = new Uint8Array(out);
  dv.setUint32(0, 0x46546c67, true); // 'glTF'
  dv.setUint32(4, 2, true);
  dv.setUint32(8, total, true);
  dv.setUint32(12, jsonPadded.length, true);
  dv.setUint32(16, 0x4e4f534a, true); // 'JSON'
  u8.set(jsonPadded, 20);
  const binStart = 20 + jsonPadded.length;
  dv.setUint32(binStart, bin.length, true);
  dv.setUint32(binStart + 4, 0x004e4942, true); // 'BIN'
  u8.set(bin, binStart + 8);
  return out;
}

/**
 * Minimal single-page PDF embedding one full-bleed JPEG (DCTDecode). Enough
 * for print-ready topo map export without a PDF library.
 *
 * @param {Uint8Array} jpegBytes
 * @param {number} pageWpt page width in PDF points
 * @param {number} pageHpt page height in PDF points
 * @param {number} imgPxW  JPEG pixel width
 * @param {number} imgPxH  JPEG pixel height
 * @returns {Uint8Array}
 */
export function toPDFWithJPEG(jpegBytes, pageWpt, pageHpt, imgPxW, imgPxH, title = 'Topographic Map') {
  return toPDFMultiJPEG([{ jpeg: jpegBytes, pxW: imgPxW, pxH: imgPxH }], pageWpt, pageHpt, title);
}

/**
 * Multi-page variant: one full-bleed JPEG per page (all pages the same size).
 * @param {Array<{jpeg: Uint8Array, pxW: number, pxH: number}>} pages
 */
export function toPDFMultiJPEG(pages, pageWpt, pageHpt, title = 'Topographic Map') {
  const enc = (s) => new TextEncoder().encode(s);
  const parts = [];
  const offsets = [0]; // object 0 is the free head
  let position = 0;
  const push = (bytes) => {
    parts.push(bytes);
    position += bytes.length;
  };
  const beginObj = () => offsets.push(position);

  push(enc('%PDF-1.4\n'));
  push(Uint8Array.from([0x25, 0xe2, 0xe3, 0xcf, 0xd3, 0x0a])); // binary-file marker comment
  beginObj();
  push(enc('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'));
  beginObj();
  const kids = pages.map((_, k) => `${3 + 3 * k} 0 R`).join(' ');
  push(enc(`2 0 obj\n<< /Type /Pages /Kids [${kids}] /Count ${pages.length} >>\nendobj\n`));
  pages.forEach(({ jpeg, pxW, pxH }, k) => {
    const pageObj = 3 + 3 * k, imgObj = pageObj + 1, contentObj = pageObj + 2;
    beginObj();
    push(enc(
      `${pageObj} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWpt.toFixed(2)} ${pageHpt.toFixed(2)}] ` +
      `/Resources << /XObject << /Im0 ${imgObj} 0 R >> >> /Contents ${contentObj} 0 R >>\nendobj\n`
    ));
    beginObj();
    push(enc(
      `${imgObj} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${pxW} /Height ${pxH} ` +
      `/ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`
    ));
    push(jpeg);
    push(enc('\nendstream\nendobj\n'));
    const content = `q ${pageWpt.toFixed(2)} 0 0 ${pageHpt.toFixed(2)} 0 0 cm /Im0 Do Q`;
    beginObj();
    push(enc(`${contentObj} 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj\n`));
  });
  const infoObj = 3 + 3 * pages.length;
  beginObj();
  push(enc(`${infoObj} 0 obj\n<< /Title (${title.replace(/[\\()]/g, '')}) /Producer (terrain-stl-generator) >>\nendobj\n`));

  const xrefStart = position;
  let xref = `xref\n0 ${offsets.length}\n0000000000 65535 f \n`;
  for (let k = 1; k < offsets.length; k++) {
    xref += `${String(offsets[k]).padStart(10, '0')} 00000 n \n`;
  }
  xref += `trailer\n<< /Size ${offsets.length} /Root 1 0 R /Info 6 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  push(enc(xref));

  const out = new Uint8Array(position);
  let off = 0;
  for (const b of parts) {
    out.set(b, off);
    off += b.length;
  }
  return out;
}

/**
 * Minimal DXF (R12) with POLYLINE entities on named layers — the dialect most
 * laser/CNC tools (LightBurn, Inkscape, Fusion) import reliably. Coordinates
 * are millimeters, y-up.
 *
 * @param {Array<{pts: [number,number][], layer: string, closed?: boolean}>} paths
 *   pts in mm with y DOWN from the sheet top (SVG convention); converted here.
 * @param {number} sheetHmm sheet height in mm (for the y flip)
 */
export function toDXF(paths, sheetHmm) {
  const L = [];
  const push = (code, value) => L.push(String(code), String(value));
  push(0, 'SECTION'); push(2, 'HEADER');
  push(9, '$ACADVER'); push(1, 'AC1009');
  push(0, 'ENDSEC');
  push(0, 'SECTION'); push(2, 'TABLES');
  push(0, 'TABLE'); push(2, 'LAYER'); push(70, 2);
  for (const [name, color] of [['CUT', 1], ['GUIDE', 5]]) {
    push(0, 'LAYER'); push(2, name); push(70, 0); push(62, color); push(6, 'CONTINUOUS');
  }
  push(0, 'ENDTAB'); push(0, 'ENDSEC');
  push(0, 'SECTION'); push(2, 'ENTITIES');
  for (const { pts, layer, closed } of paths) {
    if (!pts || pts.length < 2) continue;
    push(0, 'POLYLINE'); push(8, layer); push(66, 1); push(70, closed ? 1 : 0);
    for (const [x, y] of pts) {
      push(0, 'VERTEX'); push(8, layer);
      push(10, (+x).toFixed(3)); push(20, (sheetHmm - y).toFixed(3)); push(30, '0');
    }
    push(0, 'SEQEND');
  }
  push(0, 'ENDSEC');
  push(0, 'EOF');
  return L.join('\n') + '\n';
}

/**
 * 3MF core model files. Returns { path: contentString } entries for the caller
 * to zip (3MF is a ZIP container per the 3MF Core spec).
 */
export function to3MFFiles(positions, indices, name = 'terrain') {
  const f = (x) => +x.toFixed(5);
  const verts = [];
  for (let v = 0; v < positions.length; v += 3) {
    verts.push(`<vertex x="${f(positions[v])}" y="${f(positions[v + 1])}" z="${f(positions[v + 2])}"/>`);
  }
  const tris = [];
  for (let t = 0; t < indices.length; t += 3) {
    tris.push(`<triangle v1="${indices[t]}" v2="${indices[t + 1]}" v3="${indices[t + 2]}"/>`);
  }
  const model =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n' +
    ` <metadata name="Title">${name}</metadata>\n` +
    ' <metadata name="Application">terrain-stl-generator</metadata>\n' +
    ' <resources>\n' +
    `  <object id="1" type="model" name="${name}">\n` +
    '   <mesh>\n' +
    `    <vertices>${verts.join('')}</vertices>\n` +
    `    <triangles>${tris.join('')}</triangles>\n` +
    '   </mesh>\n' +
    '  </object>\n' +
    ' </resources>\n' +
    ' <build><item objectid="1"/></build>\n' +
    '</model>\n';

  const contentTypes =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n' +
    ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n' +
    ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n' +
    '</Types>\n';

  const rels =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n' +
    ' <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n' +
    '</Relationships>\n';

  return {
    '[Content_Types].xml': contentTypes,
    '_rels/.rels': rels,
    '3D/3dmodel.model': model,
  };
}
