/**
 * 3D-printing file format exporters. All functions are pure: they take an
 * indexed triangle mesh (positions in millimeters, CCW-wound indices) and
 * return file contents. Zipping for 3MF is done by the caller (fflate).
 */

function triangleNormal(px, py, pz, qx, qy, qz, rx, ry, rz) {
  const ux = qx - px, uy = qy - py, uz = qz - pz;
  const vx = rx - px, vy = ry - py, vz = rz - pz;
  let nx = uy * vz - uz * vy;
  let ny = uz * vx - ux * vz;
  let nz = ux * vy - uy * vx;
  const len = Math.hypot(nx, ny, nz);
  if (len > 0) { nx /= len; ny /= len; nz /= len; }
  return [nx, ny, nz];
}

/** Binary STL (units are implicitly millimeters for slicers). */
export function toBinarySTL(positions, indices, headerText = 'terrain-stl-generator') {
  const triCount = indices.length / 3;
  const buffer = new ArrayBuffer(84 + triCount * 50);
  const view = new DataView(buffer);
  const headerBytes = new TextEncoder().encode(headerText.slice(0, 80));
  new Uint8Array(buffer, 0, headerBytes.length).set(headerBytes);
  view.setUint32(80, triCount, true);
  let off = 84;
  for (let t = 0; t < triCount; t++) {
    const a = indices[t * 3] * 3, b = indices[t * 3 + 1] * 3, c = indices[t * 3 + 2] * 3;
    const n = triangleNormal(
      positions[a], positions[a + 1], positions[a + 2],
      positions[b], positions[b + 1], positions[b + 2],
      positions[c], positions[c + 1], positions[c + 2]
    );
    view.setFloat32(off, n[0], true); view.setFloat32(off + 4, n[1], true); view.setFloat32(off + 8, n[2], true);
    off += 12;
    for (const vi of [a, b, c]) {
      view.setFloat32(off, positions[vi], true);
      view.setFloat32(off + 4, positions[vi + 1], true);
      view.setFloat32(off + 8, positions[vi + 2], true);
      off += 12;
    }
    view.setUint16(off, 0, true);
    off += 2;
  }
  return buffer;
}

/** ASCII STL — much larger files, but human-readable. */
export function toAsciiSTL(positions, indices, name = 'terrain') {
  const out = [`solid ${name}`];
  const triCount = indices.length / 3;
  const f = (x) => (Object.is(x, -0) ? 0 : x).toPrecision(7);
  for (let t = 0; t < triCount; t++) {
    const a = indices[t * 3] * 3, b = indices[t * 3 + 1] * 3, c = indices[t * 3 + 2] * 3;
    const n = triangleNormal(
      positions[a], positions[a + 1], positions[a + 2],
      positions[b], positions[b + 1], positions[b + 2],
      positions[c], positions[c + 1], positions[c + 2]
    );
    out.push(`  facet normal ${f(n[0])} ${f(n[1])} ${f(n[2])}`);
    out.push('    outer loop');
    for (const vi of [a, b, c]) {
      out.push(`      vertex ${f(positions[vi])} ${f(positions[vi + 1])} ${f(positions[vi + 2])}`);
    }
    out.push('    endloop');
    out.push('  endfacet');
  }
  out.push(`endsolid ${name}`);
  return out.join('\n');
}

/** Wavefront OBJ. */
export function toOBJ(positions, indices, name = 'terrain') {
  const out = [`# ${name} — generated by terrain-stl-generator (units: mm)`, `o ${name}`];
  const f = (x) => +x.toFixed(5);
  for (let v = 0; v < positions.length; v += 3) {
    out.push(`v ${f(positions[v])} ${f(positions[v + 1])} ${f(positions[v + 2])}`);
  }
  for (let t = 0; t < indices.length; t += 3) {
    out.push(`f ${indices[t] + 1} ${indices[t + 1] + 1} ${indices[t + 2] + 1}`);
  }
  return out.join('\n');
}

/** Binary little-endian PLY. */
export function toPLY(positions, indices, name = 'terrain') {
  const vertexCount = positions.length / 3;
  const triCount = indices.length / 3;
  const header =
    'ply\nformat binary_little_endian 1.0\n' +
    `comment ${name} — generated by terrain-stl-generator (units: mm)\n` +
    `element vertex ${vertexCount}\n` +
    'property float x\nproperty float y\nproperty float z\n' +
    `element face ${triCount}\n` +
    'property list uchar uint vertex_indices\n' +
    'end_header\n';
  const headerBytes = new TextEncoder().encode(header);
  const buffer = new ArrayBuffer(headerBytes.length + vertexCount * 12 + triCount * 13);
  new Uint8Array(buffer).set(headerBytes);
  const view = new DataView(buffer);
  let off = headerBytes.length;
  for (let v = 0; v < positions.length; v++) {
    view.setFloat32(off, positions[v], true);
    off += 4;
  }
  for (let t = 0; t < indices.length; t += 3) {
    view.setUint8(off, 3);
    view.setUint32(off + 1, indices[t], true);
    view.setUint32(off + 5, indices[t + 1], true);
    view.setUint32(off + 9, indices[t + 2], true);
    off += 13;
  }
  return buffer;
}

/**
 * 3MF core model files. Returns { path: contentString } entries for the caller
 * to zip (3MF is a ZIP container per the 3MF Core spec).
 */
export function to3MFFiles(positions, indices, name = 'terrain') {
  const f = (x) => +x.toFixed(5);
  const verts = [];
  for (let v = 0; v < positions.length; v += 3) {
    verts.push(`<vertex x="${f(positions[v])}" y="${f(positions[v + 1])}" z="${f(positions[v + 2])}"/>`);
  }
  const tris = [];
  for (let t = 0; t < indices.length; t += 3) {
    tris.push(`<triangle v1="${indices[t]}" v2="${indices[t + 1]}" v3="${indices[t + 2]}"/>`);
  }
  const model =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n' +
    ` <metadata name="Title">${name}</metadata>\n` +
    ' <metadata name="Application">terrain-stl-generator</metadata>\n' +
    ' <resources>\n' +
    `  <object id="1" type="model" name="${name}">\n` +
    '   <mesh>\n' +
    `    <vertices>${verts.join('')}</vertices>\n` +
    `    <triangles>${tris.join('')}</triangles>\n` +
    '   </mesh>\n' +
    '  </object>\n' +
    ' </resources>\n' +
    ' <build><item objectid="1"/></build>\n' +
    '</model>\n';

  const contentTypes =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n' +
    ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n' +
    ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n' +
    '</Types>\n';

  const rels =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n' +
    ' <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n' +
    '</Relationships>\n';

  return {
    '[Content_Types].xml': contentTypes,
    '_rels/.rels': rels,
    '3D/3dmodel.model': model,
  };
}
